### PR TITLE
PMM-7250 Rename GetXXX -> GetXXXCredentials

### PR DESCRIPTION
**Pull request by jprukner**
[PMM-7250](https://jira.percona.com/browse/PMM-7250)

- [x] Build: https://github.com/Percona-Lab/pmm-submodules/pull/1438

- [x] Links to other linked pull requests (optional).
  - https://github.com/percona/pmm/pull/668
  - https://github.com/percona-platform/dbaas-api/pull/90
  - https://github.com/percona-platform/dbaas-controller/pull/135
  - https://github.com/Percona-Lab/pmm-api-tests/pull/178
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

### CODE REVIEW

**Comment by askomorokhov** [comment]
@jprukner  could you please check if you link correct PR https://github.com/percona-platform/dbaas-controller/pull/135  ?

And I guess we also need to fix api-tests https://github.com/Percona-Lab/pmm-api-tests/blob/ae4ba6a8f41ba4d88099751fe2a05c1fd51a2f46/management/dbaas/xtra_db_cluster_test.go#L104

**Comment by jprukner** [comment]
> @jprukner could you please check if you link correct PR [percona-platform/dbaas-controller#135](https://github.com/percona-platform/dbaas-controller/pull/135) ?

Yes, it is the correct PR. The renaming was ad hoc thing that got decided after discussion. I changed the title so it contains the change, too. 

> And I guess we also need to fix api-tests https://github.com/Percona-Lab/pmm-api-tests/blob/ae4ba6a8f41ba4d88099751fe2a05c1fd51a2f46/management/dbaas/xtra_db_cluster_test.go#L104

:+1:  I will take a look at that.

**Comment by jprukner** [comment]
@askomorokhov https://github.com/Percona-Lab/pmm-api-tests/pull/178 I modified the tests.

**Review by JiriCtvrtka — APPROVED** [review]

**Review by askomorokhov — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]
Please make sure that this will be merged with changes on the frontend side in the same time.

**Comment by jprukner** [comment]
rebased, updated deps

**Pull request merged**
