### PR TITLE
PMM-527 enable hwmon in the node exporter

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by adivinho** [comment]
https://github.com/Percona-Lab/pmm-submodules/pull/557
client - https://s3.us-east-2.amazonaws.com/pmm-build-cache/PR-BUILDS/pmm2-client/pmm2-client-PR-557-12a806d.tar.gz

**Comment by BupycHuk** [comment]
Is it ok that tests are failing?

**Comment by AlekSi** [comment]
Again, that's due to RDS instances.

**Comment by AlekSi** [comment]
I will send a PR to skip them.

**Pull request merged**
