### PR TITLE
Delete platform test as it is not a unit test

### PR DESCRIPTION
**Pull request by palash25**
These tests are not unit tests and in place of unit tests, they are being deleted in SAAS-487 already https://github.com/percona/pmm-managed/pull/694  but SAAS-487 might get delayed a bit and the new changes on saas dev will make this test fail hence deleting it

- [ ] Build: https://github.com/Percona-Lab/pmm-submodules/pull/1618

- [ ] Links to other linked pull requests (optional).  https://github.com/Percona-Lab/pmm-api-tests/pull/208
---
- [ ] Tests passed.
- [ ] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

### CODE REVIEW

**Comment by BupycHuk** [comment]
We are removing these tests because they are unit tests or because we can't get password to sign-in? How we will ensure that everything works without tests?

**Comment by palash25** [comment]
> We are removing these tests because they are unit tests or because we can't get password to sign-in?

because they are not unit tests so they shouldn't be there in the first place, they talk to an external service, the same change has been reviewed and approved as a part of this PR https://github.com/percona/pmm-managed/pull/694#discussion_r591471084

> How we will ensure that everything works without tests?

API tests are supposed to check for that

**Review by artemgavrilov — APPROVED** [review]

**Comment by artemgavrilov** [comment]
@BupycHuk @palash25  this blocks other PRs, tests are failing. It will be nice to merge it ASAP.

**Comment by palash25** [comment]
agreed, even though the original ticket is close to merge (it still might take the end of the day) I would still suggest we merge this first to unblock all the other PRs

**Review by askomorokhov — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
