### PR TITLE
Use named constant for consistency

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by AlekSi** [comment]
FWIW, we don't review draft PRs unless that was explicitly requested :)

**Comment by valyala** [comment]
> FWIW, we don't review draft PRs unless that was explicitly requested :)

Got it!

**Comment by AlekSi** [comment]
@BupycHuk It is assigned to you

**Comment by BupycHuk** [comment]
Ok, will merge once tests pass

**Pull request merged**
