### PR TITLE
SAAS-243 Update platform auth API

### PR DESCRIPTION
**Pull request by artemgavrilov**
https://jira.percona.com/browse/SAAS-243

- [x] https://github.com/percona-platform/authed/pull/30
- [x] https://github.com/percona-platform/saas/pull/11

Feature Build: https://github.com/Percona-Lab/pmm-submodules/pull/1035

Related PR's:
https://github.com/percona-platform/platform/pull/103
https://github.com/percona-platform/api-tests/pull/20

### CODE REVIEW

**Comment by artemgavrilov** [comment]
Requires https://github.com/percona-platform/authed/pull/30 on dev for passing tests.

**Comment by BupycHuk** [comment]
@artemgavrilov how can we make tests work on CI?

**Comment by artemgavrilov** [comment]
> @artemgavrilov how can we make tests work on CI?

@BupycHuk I'm waiting for deploy of related component on SaaS side. It will fix tests.

**Comment by BupycHuk** [comment]
@artemgavrilov ok, please ping me once they deployed.

**Review by palash25 — APPROVED** [review]

**Comment by artemgavrilov** [comment]
@BupycHuk it's ready, take a look please.

**Review by AlekSi — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Comment by AlekSi** [comment]
Yay, more re-assignments!

**Pull request merged**
