### PR TITLE
PMM-7863 Add version management for HAProxy

### PR DESCRIPTION
**Pull request by jprukner**
[PMM-7863](https://jira.percona.com/browse/PMM-7863)

We need to test PMM-7863 and PMM-7819 together.
- [x] Build: https://github.com/Percona-Lab/pmm-submodules/pull/1674

- [ ] Links to other linked pull requests (optional).
---
- [ ] Tests passed.
- [x] Feature build pass.
- [ ] (Re)requested review.
- [ ] Fix conflicts with target branch.
- [ ] Update API dependency.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

### CODE REVIEW

**Comment by jprukner** [comment]
I based on PMM-7358-manage-components branch. When it's merged I will change the base to PMM-2.0.

**Review by BupycHuk — CHANGES_REQUESTED** [review]
We probably should add haproxy image value into the request while creating PXC cluster.

**Comment by jprukner** [comment]
> We probably should add haproxy image value into the request while creating PXC cluster.

Yes, we do that in https://github.com/percona/pmm/pull/719/files#diff-4ab30d87114b1278e047e986f98f4a36ca383fb825dcc45fe244b702a3ee4b6cR73. I will merge that one first then this one.

**Comment by jprukner** [comment]
I am going to rebase this on PMM-2.0

**Comment by jprukner** [comment]
UI tests are failing let me investigate

**Review by BupycHuk — APPROVED** [review]

**Review by BupycHuk — CHANGES_REQUESTED** [review]
You forgot to add it here. https://github.com/percona/pmm-managed/pull/721/files#diff-46b3e78a767b0011f2658b8c48588bfa280208c708246b4d0d6916410d80ee95R210

**Review by palash25 — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
