### PR TITLE
PMM-5947 Add hostname to `--web.listen-addr`

### PR DESCRIPTION
**Pull request by valyala**
Use 127.0.0.1 hostname

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/pmm-managed?pullRequest=430) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm-managed?pullRequest=430) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm-managed?pullRequest=430) it.</sub>

**Comment by valyala** [comment]
> Please update these files too: https://github.com/percona/pmm-managed/blob/PMM-2.0/testdata/supervisord.d/prometheus.ini https://github.com/percona/pmm-managed/blob/PMM-2.0/testdata/supervisord.d/alertmanager.ini

Updated these files

**Comment by AlekSi** [comment]
Once @valyala is given access to both GitHub Percona-Lab/pmm-submodules and Confluence, I will show him how to make feature builds.

**Comment by valyala** [comment]
> Once @valyala is given access to both GitHub Percona-Lab/pmm-submodules and Confluence, I will show him how to make feature builds.

It looks like I have access to [Percona-Lab/pmm-submodules](https://github.com/Percona-Lab/pmm-submodules) and Confluence, so let's proceed further when you have free time.

**Comment by valyala** [comment]
The PR has been moved to https://github.com/percona/pmm-managed/pull/436

**Pull request closed without merging**
