### PR TITLE
SAAS-73 Improve debug logging

### PR DESCRIPTION
**Pull request by artemgavrilov**
- https://jira.percona.com/browse/SAAS-73

That PR simplifies local testing. 

FB: https://github.com/Percona-Lab/pmm-submodules/pull/861

### CODE REVIEW

**Comment by AlekSi** [comment]
We have `s.l.Debugf("Request: %+v", req)` below. I think we should change it to use `proto.MarshalTextString` and remove explicit UUID logging.

**Comment by artemgavrilov** [comment]
@AlekSi I tried, request id field is byte slice, so after `proto.MarshalTextString` we have 
```
Request: events: <
  id: "\206b5y{jB\342\253VO\2145\0073\264".  
  time: <
    seconds: 1589970331
    nanos: 611069400
  >
  event: <
    type_url: "percona.platform.telemetry.events.pmm.v1.ServerUptimeEvent"
    binary: "\n\020\324\316\300i\312\"D\010\220\252\001\375B\233\245\207\022\0262.6.1-4-g76528af-dirty\032\007\010d\020\330\240\226\" \001"
  >
> 
```

**Comment by AlekSi** [comment]
Ok, makes sense

**Comment by artemgavrilov** [comment]
So, I leave separated log for UUID?

**Pull request merged**
